on: 
  push

name: generate_pkg_list

jobs:
  generate_pkg_list:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
        
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, bioc: 'devel'}
        - {os: windows-latest, bioc: 'devel'}
        - {os: ubuntu-latest, bioc: 'devel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc }}
      
      - name: Build and test environment
        run: |
          BiocManager::install(c("basilisk", "basilisk.utils"))
          
          deps <- c(
              "python==3.10", 
              "scvelo==0.3.1", 
              "pillow==9.2"
          )
          
          ## Test with package list generated with new conda
          if (basilisk.utils::isLinux()) {
              deps <- c("_libgcc_mutex==0.1",
                        "_openmp_mutex==4.5",
                        "absl-py==2.1.0",
                        "anndata==0.10.4",
                        "annotated-types==0.6.0",
                        "anyio==3.7.1",
                        "array-api-compat==1.4.1",
                        "arrow==1.3.0",
                        "backoff==2.2.1",
                        "beautifulsoup4==4.12.3",
                        "blessed==1.19.1",
                        "brotli==1.1.0",
                        "brotli-bin==1.1.0",
                        "brotli-python==1.1.0",
                        "bzip2==1.0.8",
                        "c-ares==1.25.0",
                        "ca-certificates==2023.12.12",
                        "cachecontrol==0.13.1",
                        "cachecontrol-with-filecache==0.13.1",
                        "cached-property==1.5.2",
                        "cached_property==1.5.2",
                        "certifi==2023.11.17",
                        "cffi==1.16.0",
                        "charset-normalizer==3.3.2",
                        "chex==0.1.8",
                        "cleo==2.1.0",
                        "click==8.1.7",
                        "colorama==0.4.6",
                        "contextlib2==21.6.0",
                        "contourpy==1.2.0",
                        "crashtest==0.4.1",
                        "croniter==1.4.1",
                        "cryptography==41.0.7",
                        "cycler==0.12.1",
                        "dateutils==0.6.12",
                        "dbus==1.13.6",
                        "deepdiff==6.7.1",
                        "distlib==0.3.8",
                        "dm-tree==0.1.8",
                        "docrep==0.3.2",
                        "dulwich==0.21.7",
                        "et_xmlfile==1.1.0",
                        "exceptiongroup==1.2.0",
                        "expat==2.5.0",
                        "fastapi==0.109.0",
                        "filelock==3.13.1",
                        "flax==0.6.1",
                        "fonttools==4.47.2",
                        "freetype==2.12.1",
                        "fsspec==2023.12.2",
                        "get-annotations==0.1.2",
                        "gettext==0.21.1",
                        "gmp==6.3.0",
                        "gmpy2==2.1.2",
                        "h11==0.14.0",
                        "h5py==3.10.0",
                        "hdf5==1.14.3",
                        "icu==73.2",
                        "idna==3.6",
                        "importlib-metadata==7.0.1",
                        "importlib_metadata==7.0.1",
                        "inquirer==3.1.4",
                        "itsdangerous==2.1.2",
                        "jaraco.classes==3.3.0",
                        "jax==0.4.13",
                        "jaxlib==0.4.12",
                        "jeepney==0.8.0",
                        "jinja2==3.1.3",
                        "joblib==1.3.2",
                        "jpeg==9e",
                        "keyring==24.3.0",
                        "keyutils==1.6.1",
                        "kiwisolver==1.4.5",
                        "krb5==1.21.2",
                        "lcms2==2.15",
                        "ld_impl_linux-64==2.40",
                        "lerc==4.0.0",
                        "libabseil==20230125.3",
                        "libaec==1.1.2",
                        "libblas==3.9.0",
                        "libbrotlicommon==1.1.0",
                        "libbrotlidec==1.1.0",
                        "libbrotlienc==1.1.0",
                        "libcblas==3.9.0",
                        "libcurl==8.5.0",
                        "libdeflate==1.17",
                        "libedit==3.1.20191231",
                        "libev==4.33",
                        "libexpat==2.5.0",
                        "libffi==3.4.2",
                        "libgcc-ng==13.2.0",
                        "libgfortran-ng==13.2.0",
                        "libgfortran5==13.2.0",
                        "libglib==2.78.3",
                        "libgomp==13.2.0",
                        "libgrpc==1.56.2",
                        "libhwloc==2.9.3",
                        "libiconv==1.17",
                        "liblapack==3.9.0",
                        "libllvm14==14.0.6",
                        "libnghttp2==1.58.0",
                        "libnsl==2.0.1",
                        "libopenblas==0.3.25",
                        "libpng==1.6.39",
                        "libprotobuf==4.23.3",
                        "libsqlite==3.44.2",
                        "libssh2==1.11.0",
                        "libstdcxx-ng==13.2.0",
                        "libtiff==4.5.0",
                        "libuuid==2.38.1",
                        "libuv==1.46.0",
                        "libwebp-base==1.3.2",
                        "libxcb==1.13",
                        "libxcrypt==4.4.36",
                        "libxml2==2.12.4",
                        "libzlib==1.2.13",
                        "lightning==2.0.9.post0",
                        "lightning-cloud==0.5.39",
                        "lightning-utilities==0.10.1",
                        "llvmlite==0.41.1",
                        "loompy==3.0.6",
                        "markdown-it-py==3.0.0",
                        "markupsafe==2.1.4",
                        "matplotlib-base==3.8.2",
                        "mdurl==0.1.2",
                        "ml-collections==0.1.1",
                        "ml_dtypes==0.3.2",
                        "more-itertools==10.2.0",
                        "mpc==1.3.1",
                        "mpfr==4.2.1",
                        "mpmath==1.3.0",
                        "msgpack-python==1.0.7",
                        "mudata==0.2.3",
                        "multipledispatch==0.6.0",
                        "munkres==1.1.4",
                        "natsort==8.4.0",
                        "ncurses==6.4",
                        "networkx==3.2.1",
                        "nomkl==1.0",
                        "numba==0.58.1",
                        "numpy==1.26.3",
                        "numpy_groupies==0.10.2",
                        "numpyro==0.13.2",
                        "openjpeg==2.5.0",
                        "openpyxl==3.1.2",
                        "openssl==3.2.0",
                        "opt_einsum==3.3.0",
                        "optax==0.1.8",
                        "ordered-set==4.1.0",
                        "orjson==3.9.10",
                        "packaging==23.2",
                        "pandas==2.2.0",
                        "patsy==0.5.6",
                        "pcre2==10.42",
                        "pexpect==4.8.0",
                        "pillow==9.2.0",
                        "pip==23.3.2",
                        "pkginfo==1.9.6",
                        "platformdirs==3.11.0",
                        "poetry==1.7.1",
                        "poetry-core==1.8.1",
                        "poetry-plugin-export==1.6.0",
                        "psutil==5.9.8",
                        "pthread-stubs==0.4",
                        "ptyprocess==0.7.0",
                        "pycparser==2.21",
                        "pydantic==2.1.1",
                        "pydantic-core==2.4.0",
                        "pygments==2.17.2",
                        "pyjwt==2.8.0",
                        "pynndescent==0.5.11",
                        "pyparsing==3.1.1",
                        "pyproject_hooks==1.0.0",
                        "pyro-api==0.1.2",
                        "pyro-ppl==1.8.6",
                        "pysocks==1.7.1",
                        "python==3.10.13",
                        "python-build==1.0.3",
                        "python-dateutil==2.8.2",
                        "python-editor==1.0.4",
                        "python-fastjsonschema==2.19.1",
                        "python-installer==0.7.0",
                        "python-multipart==0.0.6",
                        "python-tzdata==2023.4",
                        "python_abi==3.10",
                        "pytorch==2.0.0",
                        "pytorch-lightning==2.1.3",
                        "pytz==2023.3.post1",
                        "pyyaml==6.0.1",
                        "rapidfuzz==3.6.1",
                        "re2==2023.03.02",
                        "readchar==4.0.5",
                        "readline==8.2",
                        "requests==2.31.0",
                        "requests-toolbelt==1.0.0",
                        "rich==13.7.0",
                        "scanpy==1.9.6",
                        "scikit-learn==1.1.3",
                        "scipy==1.12.0",
                        "scvelo==0.3.1",
                        "scvi-tools==1.0.4",
                        "seaborn==0.13.1",
                        "seaborn-base==0.13.1",
                        "secretstorage==3.3.3",
                        "session-info==1.0.0",
                        "setuptools==69.0.3",
                        "shellingham==1.5.4",
                        "six==1.16.0",
                        "sleef==3.5.1",
                        "sniffio==1.3.0",
                        "soupsieve==2.5",
                        "sparse==0.15.1",
                        "sqlite==3.41.2",
                        "starlette==0.35.0",
                        "starsessions==1.3.0",
                        "statsmodels==0.14.1",
                        "stdlib-list==0.10.0",
                        "sympy==1.12",
                        "tbb==2021.11.0",
                        "threadpoolctl==3.2.0",
                        "tk==8.6.13",
                        "tomli==2.0.1",
                        "tomlkit==0.12.3",
                        "toolz==0.12.0",
                        "torchmetrics==1.2.1",
                        "tqdm==4.66.1",
                        "traitlets==5.14.1",
                        "trove-classifiers==2024.1.8",
                        "types-python-dateutil==2.8.19.20240106",
                        "typing-extensions==4.9.0",
                        "typing_extensions==4.9.0",
                        "tzdata==2023d",
                        "umap-learn==0.5.5",
                        "unicodedata2==15.1.0",
                        "urllib3==2.1.0",
                        "uvicorn==0.26.0",
                        "virtualenv==20.25.0",
                        "wcwidth==0.2.13",
                        "websocket-client==1.7.0",
                        "websockets==12.0",
                        "wheel==0.42.0",
                        "xarray==2024.1.0",
                        "xlrd==1.2.0",
                        "xorg-libxau==1.0.11",
                        "xorg-libxdmcp==1.1.3",
                        "xz==5.4.5",
                        "yaml==0.2.5",
                        "zipp==3.17.0",
                        "zlib==1.2.13",
                        "zstd==1.5.5")
          }

          basilisk.utils::installConda()
          basilisk::setupBasiliskEnv(
            envpath = file.path(".", "scvelo-basilisk-env"),
            packages = deps,
            channels = "conda-forge")
          res <- basilisk::basiliskRun(
            env = file.path(".", "scvelo-basilisk-env"),
            fun = function() {
                scv <- reticulate::import("scvelo")
                scv$`__version__`
            })
          print(res)
          print(basilisk::listPackages(env = file.path(".", "scvelo-basilisk-env")))
        shell: Rscript {0}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0

      - name: List content of environment
        run: conda list -p ./scvelo-basilisk-env
      
      - name: List content of environment in format suitable for pasting into R
        run: |
          conda list -p ./scvelo-basilisk-env | tail -n +4 |\
          tr -s ' ' | cut -f1,2 -d' ' |\
          sed -e 's/ /==/' -e 's/^..*$/"&",/' -e '$ s/.$/)/' -e '1s/^/c(/'
