on: 
  push

name: generate_pkg_list

jobs:
  generate_pkg_list:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
        
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, bioc: 'devel', miniconda: 'py39_22.11.1-1'}
        - {os: macOS-12, bioc: 'devel', miniconda: 'py39_22.11.1-1'}
        - {os: windows-latest, bioc: 'devel', miniconda: 'py39_4.12.0'}
        - {os: ubuntu-latest, bioc: 'devel', miniconda: 'py39_4.12.0'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BASILISK_MINICONDA_VERSION: ${{ matrix.config.miniconda }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc }}
      
      - name: Build and test environment
        run: |
          BiocManager::install(c("basilisk", "basilisk.utils"))
          
          deps <- c(
              "scvelo==0.2.5",
              "matplotlib==3.7.3", # https://stackoverflow.com/questions/77128061/ydata-profiling-profilereport-attributeerror-module-matplotlib-cbook-has-no
              "tqdm==4.66.4", # required for progress bar
              "ipywidgets==8.1.2", # required for progress bar
              "jupyterlab==4.2.0", # required for progress bar
              "numpy==1.23.1" # https://github.com/OpenTalker/video-retalking/issues/35
          )
          
          basilisk.utils::installConda()
          basilisk::setupBasiliskEnv(
            envpath = file.path(".", "scvelo-basilisk-env"),
            packages = deps,
            channels = "conda-forge")
          res <- basilisk::basiliskRun(
            env = file.path(".", "scvelo-basilisk-env"),
            fun = function() {
                scv <- reticulate::import("scvelo")
                scv$`__version__`
            })
          print(res)
          print(basilisk::listPackages(env = file.path(".", "scvelo-basilisk-env")))
        shell: Rscript {0}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0

      - name: List content of environment
        run: conda list -p ./scvelo-basilisk-env
      
      - name: List content of environment in format suitable for pasting into R
        run: |
          conda list -p ./scvelo-basilisk-env | tail -n +4 |\
          tr -s ' ' | cut -f1,2 -d' ' |\
          sed -e 's/ /==/' -e 's/^..*$/"&",/' -e '$ s/.$/)/' -e '1s/^/c(/'
